### ISSUE TITLE
calendar failure

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-9.0-SPANISH#12]
@ingbrzy
java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.android.calendar.common.event.schema.AgendaEvent)
	at android.os.Parcel.writeSerializable(Parcel.java)
	at android.os.Parcel.writeValue(Parcel.java)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java)
	at android.os.Bundle.writeToParcel(Bundle.java)
	at android.os.Parcel.writeBundle(Parcel.java)
	at android.app.FragmentState.writeToParcel(Fragment.java)
	at android.os.Parcel.writeTypedArray(Parcel.java)
	at android.app.FragmentManagerState.writeToParcel(FragmentManager.java)
	at android.os.Parcel.writeParcelable(Parcel.java)
	at android.os.Parcel.writeValue(Parcel.java)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java)
	at android.os.Bundle.writeToParcel(Bundle.java)
	at android.os.Parcel.writeBundle(Parcel.java)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java)
	at android.os.Handler.handleCallback(Handler.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
Caused by: java.io.NotSerializableException: com.android.calendar.common.event.schema.Attendee
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1224)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	at java.util.HashMap.writeObject(HashMap.java:1418)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:977)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1536)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1584)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1549)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1472)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1218)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:346)
	... 24 more

**Comment by ingbrzy** [comment]
Which device? Which ROM version? When it crash? Is it ok on English language?

**Comment by Infante007** [comment]
It's true, sorry.
My phone is a Mi5 and in the English language also gives me failure.
I have the last weekly 7.10.26.
It hangs up when I want to edit a reminder and I want to change the time in Reminders and Repeat

**Comment by Infante007** [comment]
Hello @ingbrzy , is there a problem?

**Comment by ingbrzy** [comment]
not a translation issue
