### ISSUE TITLE
Bug scanner

### ISSUE THREAD

**Issue by Infante007** [ingbrzy/MA-XML-9.0-SPANISH#78]
Hello @ingbrzy the scanner application have a bug,
in the option documents gives error and also in English language

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/miuistatssdkshared.jar", zip file "/system/framework/android.test.runner.jar", zip file "/system/priv-app/MiuiScanner/MiuiScanner.apk"],nativeLibraryDirectories=[/system/priv-app/MiuiScanner/lib/arm64, /system/fake-libs64, /system/priv-app/MiuiScanner/MiuiScanner.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]] couldn't find "libQuadrangleRecognizer.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:972)
	at java.lang.System.loadLibrary(System.java:1530)
	at com.xiaomi.recognizer.Quadrangle.<clinit>(Quadrangle.java)
	at com.xiaomi.recognizer.Quadrangle.detectByteArray(Quadrangle.java)
	at com.xiaomi.scanner.module.DocumentModule$DocumentHandler.detectPreviewData(DocumentModule.java)
	at com.xiaomi.scanner.module.DocumentModule$DocumentHandler.handleMessage(DocumentModule.java)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.os.HandlerThread.run(HandlerThread.java)

**Comment by Infante007** [comment]
Thx @ingbrzy
